export interface Person {
  id: string;
  name: string;
  hanjaName: string;
  courtesyName?: string; // 자 (字)
  pseudonym?: string; // 호 (號)
  generation: number; // 몇 세손/세
  birthDeath?: string;
  branch: string; // 분파 (예: 시조계, 수곡파 등)
  title?: string; // 관직 및 증직
  category: 'progenitor' | 'scholar' | 'patriot' | 'official' | 'ancestor';
  summary: string;
  achievements: string[];
  writings?: string[];
  relics?: string[];
  fatherId?: string;
}

export interface GenealogyNode {
  id: string;
  name: string;
  hanjaName: string;
  generation: number;
  branch: string;
  title?: string;
  pseudonym?: string;
  courtesyName?: string;
  birthDeath?: string;
  fatherId?: string;
  childrenIds?: string[];
  isSubBranchHead?: boolean; // 파조 여부
  note?: string;
  jokboCode?: number; // 전주류씨 대동보 고유 식별 코드 (scode)
  jokboBook?: number; // 대동보 책 권수
  jokboPage?: number; // 대동보 페이지
  subBranchKey?: 'root' | 'jongpa' | 'samsan' | 'dongam' | 'chiljam'; // 계통 분류 키
}

export interface ArchiveItem {
  id: string;
  title: string;
  hanjaTitle?: string;
  category: 'document' | 'historic_site' | 'submerged_history' | 'calligraphy' | 'photo';
  categoryLabel: string;
  dateOrEra: string;
  location?: string;
  description: string;
  significance: string;
  imageUrl?: string;
  tag: string[];
  sourceOrKeeper: string;
}

export interface TimelineEvent {
  year: string;
  title: string;
  category: 'origin' | 'settlement' | 'achievement' | 'tragedy' | 'archive';
  description: string;
}

// 1. 주요 인물 데이터 (시조부터 고려·조선·독립운동 20대 대표 인물)
export const PEOPLE: Person[] = [
  {
    id: 'ryu-hon',
    name: '류혼',
    hanjaName: '柳渾',
    generation: 1,
    branch: '전주류씨 시조',
    title: '고려 완산백(完山伯)',
    category: 'progenitor',
    summary: '전주류씨의 시조. 고려 왕조에서 완산백(完山伯)에 봉해져 후손들이 전주(완산)를 본관으로 삼아 번창하게 되었습니다.',
    achievements: [
      '전주류씨의 시조로서 천년 가문의 터전을 닦음',
      '고려조 완산백에 봉해지며 동방 명문가로서의 기틀을 확립'
    ],
    relics: ['전주 시조 묘역 및 제단'],
  },
  {
    id: 'ryu-seub',
    name: '류습',
    hanjaName: '柳濕',
    generation: 1,
    branch: '전주류씨 중흥조',
    title: '완산부원군(完山府院君), 참지정사',
    category: 'progenitor',
    summary: '고려 말 참지정사를 지내고 완산부원군에 추봉된 중흥조. 다섯 아들(극서·극간·극삼·극송·극제)이 모두 과거에 급제하여 ‘오자급제(五子及第)’의 영예로 가문을 크게 일으켰습니다.',
    achievements: [
      '오자급제의 위업으로 가문을 고려 말·조선 초 최고 사대부 대족으로 도약시킴',
      '삼한국대부인 전주 전씨와 함께 가문의 번영 기틀 완성'
    ],
  },
  {
    id: 'ryu-geukseo',
    name: '류극서',
    hanjaName: '柳克恕',
    generation: 2,
    branch: '묵계공파 파조 (안동계통)',
    title: '집현전 직제학, 이조판서 추증',
    category: 'scholar',
    summary: '고려 말 정당문학을 거쳐 조선 초 집현전 직제학을 역임한 학자이자 청백리. 수곡파의 직계 선조로서 영남 안동 입향의 선대 교두보를 마련하였습니다.',
    achievements: [
      '조선 초 유학 진흥과 집현전 학문적 기틀 확립',
      '묵계공파의 파조로서 영남 사림으로의 가풍 전환 계기 마련'
    ],
  },
  {
    id: 'ryu-uison',
    name: '류의손',
    hanjaName: '柳義孫',
    courtesyName: '효숙(孝叔)',
    pseudonym: '회헌(檜軒)',
    generation: 4,
    birthDeath: '1398 ~ 1450',
    branch: '묵계공파',
    title: '집현전 부제학, 예조참판, 이조참판',
    category: 'scholar',
    summary: '세종 대 집현전 부제학, 예조참판, 이조참판 등을 역임한 당대 최고 명신. 훈민정음 창제와 세종 대 국가 예악(禮樂) 정비에 중추적 역할을 하였으며, 안동 기양서당 내 세덕사(世德祠) 주벽으로 제향되고 있습니다.',
    achievements: [
      '세종 대 집현전 부제학으로 집현전 학사들을 이끌며 학술과 문풍 진흥',
      '훈민정음 창제 및 운서 편찬, 4국 사행을 통한 외교 공헌',
      '청백과 충절의 가풍으로 안동 세덕사에 배향'
    ],
    writings: ['회헌유고(檜軒遺稿)'],
    relics: ['안동 기양서당 세덕사(世德祠) 배향'],
  },
  {
    id: 'ryu-seong',
    name: '류성',
    hanjaName: '柳城',
    courtesyName: '여중(汝中)',
    generation: 8,
    birthDeath: '1533 ~ 1560',
    branch: '수곡파 (무실 입향조)',
    title: '성균생원, 증 사헌부 집의',
    category: 'progenitor',
    summary: '전주류씨 무실(수곡) 마을의 실질적 입향조. 의성 김씨 청계 김진 선생의 사위이자 학봉 김성일의 자형으로, 안동 임동면 수곡리에 처음 터를 잡아 500년 수곡파 집성촌의 역사를 열었습니다.',
    achievements: [
      '안동 임동면 무실마을(수곡리)에 입향하여 수곡파 세거의 기틀 개척',
      '의성 김씨 명문가와의 결연을 통해 퇴계 학맥과 가학 전승의 교두보 마련',
      '부인 의성 김씨의 정절로 인조 임금으로부터 무실정려각(務實旌閭閣) 하사'
    ],
    relics: ['무실정려각(경북 민속문화유산 제48호)'],
  },
  {
    id: 'ryu-bokgi',
    name: '류복기',
    hanjaName: '柳復起',
    courtesyName: '경순(景純)',
    pseudonym: '기봉(岐峯)',
    generation: 9,
    birthDeath: '1555 ~ 1617',
    branch: '수곡파 파조 (무실 중시조)',
    title: '사헌부 지평 증직, 임진왜란 예안의병장',
    category: 'patriot',
    summary: '무실마을을 영남 유학의 대표 문향으로 일으킨 수곡파의 중시조. 임진왜란이 일어나자 예안에서 의병을 일으켜 영남 북부 내륙을 수호하였으며, 1615년 기양서당을 창건하여 후학을 양성했습니다.',
    achievements: [
      '1592년 임진왜란 예안 의병장으로 창의하여 낙동강 동원 방어선 사수',
      '외숙인 학봉 김성일과 한강 정구에게 수학하여 퇴계 정통 학맥 계승',
      '기양서당(岐陽書堂)을 창건하여 수곡파 가학(家學)의 교육 구심점 확립'
    ],
    writings: ['기봉집(岐峯集, 유네스코 세계기록유산 유교책판)'],
    relics: ['기봉정사(경북 문화유산자료)', '기양서당(경북 민속문화유산)', '무실종택'],
  },
  {
    id: 'ryu-bokrip',
    name: '류복립',
    hanjaName: '柳復立',
    courtesyName: '군량(君良)',
    pseudonym: '구암(龜巖)',
    generation: 9,
    birthDeath: '1558 ~ 1593',
    branch: '수곡파',
    title: '이조판서 추증, 임진왜란 진주성 순절 충신',
    category: 'patriot',
    summary: '기봉 류복기의 아우. 1592년 형과 함께 예안의병으로 창의한 뒤, 1593년 제2차 진주성 전투에서 창의사 김천일·최경회 등과 함께 성을 지키다 남강에 투신하여 장렬하게 순절한 호국 충신입니다.',
    achievements: [
      '임진왜란 제2차 진주성 전투에서 왜적 10만 대군에 맞서 결사항전 후 순절',
      '선조 조 정려(旌閭) 하사 및 이조판서 추증',
      '진주 창열사(彰烈祠) 및 안동 충현사 배향'
    ],
    relics: ['진주 창열사 배향', '충신 정려각'],
  },
  {
    id: 'ryu-seunghyeon',
    name: '류승현',
    hanjaName: '柳升鉉',
    courtesyName: '회백(晦伯)',
    pseudonym: '용와(慵窩)',
    generation: 14,
    birthDeath: '1680 ~ 1746',
    branch: '수곡파 (용와문중)',
    title: '사헌부 대사간, 승정원 동부승지',
    category: 'scholar',
    summary: '조선 후기 수곡파의 학문적 전성기를 연 석학. 아우 류관현과 함께 대과에 급제하여 명성을 떨쳤으며, 대사간을 지내며 강직한 언론을 폈습니다. 가족과 문중이 함께 학문을 닦는 독자적 가학 전통을 수립했습니다.',
    achievements: [
      '아우 양파 류관현과 함께 문과 급제하여 수곡파를 중앙 정계와 학계의 명문으로 도약시킴',
      '사헌부 대사간으로서 영조 대 탕평 정국의 직간 수행',
      '『용와집』을 저술하여 성리학과 예학 연구 심화'
    ],
    writings: ['용와집(慵窩集, 유네스코 세계기록유산 유교책판)'],
    relics: ['용와종택 및 침간정(경북 민속문화유산 제18호, 구미 일선리 이건)'],
  },
  {
    id: 'ryu-gwanhyeon',
    name: '류관현',
    hanjaName: '柳觀鉉',
    courtesyName: '빈백(賓伯)',
    pseudonym: '양파(陽坡)',
    generation: 14,
    birthDeath: '1692 ~ 1764',
    branch: '수곡파',
    title: '사헌부 대사헌, 홍문관 부제학',
    category: 'official',
    summary: '용와 류승현의 아우로 대사헌, 부제학을 지낸 명신. 형제간 우애가 깊고 학문이 뛰어나 영남 사림의 칭송을 받았으며, 셋째 아들이 바로 『상변통고』를 지은 동암 류장원 선생입니다.',
    achievements: [
      '영조 연간 대사헌과 부제학을 역임하며 영남 남인을 대표하는 관료로 활약',
      '아들 류장원을 비롯한 후학들을 훈도하여 영남 예학의 황금기를 개척'
    ],
    writings: ['양파집(陽坡集)'],
  },
  {
    id: 'ryu-jungwon',
    name: '류정원',
    hanjaName: '柳正源',
    courtesyName: '순백(淳伯)',
    pseudonym: '삼산(三山)',
    generation: 15,
    birthDeath: '1687 ~ 1761',
    branch: '수곡파 (삼산문중)',
    title: '사헌부 대사헌, 이조참판, 홍문관 제학',
    category: 'scholar',
    summary: '조선 후기 영남학파를 대표하는 대유학자이자 명신. 영조 대 대사헌과 이조참판을 지내며 탕평책의 허실을 날카롭게 비판하는 강직한 상소를 올렸고, 퇴계 이황의 학통을 심화시켜 『삼산집』 14권을 남겼습니다.',
    achievements: [
      '영조 대 대사헌으로 붕당의 폐해를 극복하는 올곧은 직언을 서슴지 않음',
      '퇴계 성리학을 계승·발전시켜 영남 유학의 사상적 정통성을 확립',
      '수곡마을을 영남 제일의 학문과 절의의 문향으로 위상을 드높임'
    ],
    writings: ['삼산집(三山集 14권, 한국국학진흥원 장판각 기탁)'],
    relics: ['삼산정(경북 유형문화유산)', '삼산종택'],
  },
  {
    id: 'ryu-jangwon',
    name: '류장원',
    hanjaName: '柳長源',
    courtesyName: '순우(純禹)',
    pseudonym: '동암(東巖)',
    generation: 15,
    birthDeath: '1724 ~ 1796',
    branch: '수곡파 (동암문중)',
    title: '성균관 진사, 조선 예학의 거봉',
    category: 'scholar',
    summary: '양파 류관현의 아들이자 대산 이상정의 수제자. 조선 후기 예학의 최고 표준서이자 2015년 유네스코 세계기록유산으로 등재된 『상변통고(常變通攷)』 22권 11책을 저술하여 조선 사림의 예학 논쟁을 집대성했습니다.',
    achievements: [
      '조선 예학의 불후의 명저 『상변통고』 22권을 저술하여 유네스코 세계기록유산 등재',
      '퇴계-한강-이상정으로 이어지는 영남 성리학의 예론을 체계화',
      '사림의 모든 의례 절차와 전례 쟁점을 명쾌하게 정리한 표준서 확립'
    ],
    writings: ['상변통고(常變通攷 22권, 유네스코 세계기록유산)', '동암문집(東巖文集)'],
    relics: ['동암정(경북 문화유산자료 제62호, 구미 일선리 이건)'],
  },
  {
    id: 'ryu-hwimun',
    name: '류휘문',
    hanjaName: '柳徽文',
    courtesyName: '공서(公舒)',
    pseudonym: '호고와(互古窩)',
    generation: 18,
    birthDeath: '1773 ~ 1827',
    branch: '수곡파 (호고와문중)',
    title: '조선 후기 성리학 심성론의 대가',
    category: 'scholar',
    summary: '정재 류치명의 종형으로, 19세기 영남 성리학파를 대표하는 심성론(心性論)의 대가. 퇴계학을 정밀하게 연구하여 심체(心體)와 정(情)의 구조를 분석한 『호고와집』을 남겼습니다.',
    achievements: [
      '조선 후기 영남 성리학 심성론의 정밀한 이론 체계를 구축',
      '종제인 정재 류치명과 학문적으로 깊이 교유하며 19세기 영남학풍 주도',
      '문집 목판이 유네스코 세계기록유산 유교책판으로 등재'
    ],
    writings: ['호고와집(互古窩集, 유네스코 세계기록유산 유교책판)'],
    relics: ['호고와종택(안동 임동면)'],
  },
  {
    id: 'ryu-chimyeong',
    name: '류치명',
    hanjaName: '柳致明',
    courtesyName: '성백(誠伯)',
    pseudonym: '정재(定齋)',
    generation: 18,
    birthDeath: '1777 ~ 1861',
    branch: '수곡파 (정재문중)',
    title: '사헌부 대사헌, 이조참판, 영남학파 종장(宗匠)',
    category: 'scholar',
    summary: '19세기 영남 퇴계학파의 종장(宗匠)이자 사림의 영수. 대사헌과 이조참판을 역임하며 올곧은 유학자의 절의를 지켰고, 수많은 문도를 길러내 구한말 의병운동과 척사위정 운동의 사상적 수원지가 되었습니다.',
    achievements: [
      '19세기 영남 남인 사림의 종장으로 추앙받으며 퇴계학통을 확고히 수호',
      '이조참판 재임 시 나라의 폐정을 개혁하는 직언을 올려 사림의 사표가 됨',
      '문하에서 김흥락, 류필영 등 한말 의병과 독립운동을 이끈 거유들을 대거 배출',
      '『정재선생문집』 32권이 경북 유형문화유산 제171호 및 유네스코 세계기록유산으로 등재'
    ],
    writings: ['정재집(定齋集 32권 16책, 유네스코 세계기록유산)', '대학동자문', '예의고상'],
    relics: ['안동 정재종택(경북 기념물 제170호)', '정재문집 목판(경북 유형문화유산 제171호)'],
  },
  {
    id: 'ryu-jumok',
    name: '류주목',
    hanjaName: '柳疇睦',
    courtesyName: '치용(稚容)',
    pseudonym: '묵재(默齋)',
    generation: 19,
    birthDeath: '1813 ~ 1872',
    branch: '수곡파',
    title: '조선 말기 유학자',
    category: 'scholar',
    summary: '수곡파 가문의 학풍을 계승하고 족보 편찬과 선조들의 유문 정리에 평생을 바친 학자. 삼산집과 기봉집의 속집 간행 및 수곡파 세보의 정본화에 결정적으로 기여했습니다.',
    achievements: [
      '수곡파 세보(족보) 중간(重刊)을 주도하여 가문 계보 정본 확립',
      '선조들의 유고와 고문서를 체계적으로 수집·정리하여 멸실 방지'
    ],
    writings: ['묵재문집(默齋文集)'],
  },
  {
    id: 'ryu-pilyoung',
    name: '류필영',
    hanjaName: '柳必永',
    courtesyName: '무백(茂伯)',
    pseudonym: '서산(西山)',
    generation: 20,
    birthDeath: '1841 ~ 1924',
    branch: '수곡파',
    title: '통정대부 비서원승, 파리장서 독립청원 서명인 (건국포장)',
    category: 'patriot',
    summary: '정재 류치명의 고제(高弟)이자 한말의 거유(巨儒). 1919년 3·1운동 직후 전국의 유림 137인이 파리강화회의에 조국의 독립을 청원한 파리장서(巴里長書)에 서명하여 옥고를 치렀습니다.',
    achievements: [
      '1919년 영호남 유림 파리장서 독립청원서에 서명하고 항일 구국투쟁 전개',
      '일제의 온갖 회유와 협박을 물리치고 선비의 지조와 항일 민족의식을 굳건히 수호',
      '정부로부터 건국포장 추서'
    ],
    writings: ['서산집(西山集 20권)'],
    relics: ['파리장서 국한문 원본 사본', '서산 유묵'],
  },
  {
    id: 'ryu-yeonseong',
    name: '류연성',
    hanjaName: '柳淵成',
    courtesyName: '치성(稚成)',
    pseudonym: '추해(秋海)',
    generation: 20,
    birthDeath: '1860 ~ 1919',
    branch: '수곡파',
    title: '3·1운동 순국지사 (건국훈장 애국장)',
    category: 'patriot',
    summary: '안동 임동면 편항 장터 만세운동의 주도자. 1919년 3월 21일 수천 명의 군중과 함께 주재소를 습격하고 대한독립만세를 외치다 일본 경찰의 흉탄에 체포되어 대구형무소에서 옥중 순국하였습니다.',
    achievements: [
      '1919년 3월 21일 안동 임동면 편항 장터 만세의거를 주도하여 영남 3·1운동 격화',
      '일제의 가혹한 고문에도 굴하지 않고 옥중에서 장렬히 순국',
      '1991년 건국훈장 애국장 추서'
    ],
    relics: ['임동 만대의숙 및 독립만세기념비'],
  },
  {
    id: 'ryu-insik',
    name: '류인식',
    hanjaName: '柳寅植',
    courtesyName: '옥관(玉寬)',
    pseudonym: '동산(東山)',
    generation: 21,
    birthDeath: '1865 ~ 1928',
    branch: '수곡파 (삼산문중)',
    title: '신간회 안동지회장, 협동학교 설립자 (건국훈장 독립장)',
    category: 'patriot',
    summary: '안동 혁신 유림의 선구자이자 독립운동의 거두. 삼산 류정원의 직계 후손으로, 1907년 협동학교를 설립하여 애국 계몽운동을 폈고, 만주 서간도로 망명하여 신흥무관학교 설립에 참여하였으며 신간회 안동지회장을 역임했습니다.',
    achievements: [
      '1907년 안동 내앞마을에 협동학교(協東學校)를 세워 근대적 독립군 양성의 요람 구축',
      '1911년 만주 서간도로 망명하여 경학사 및 신흥무관학교 기틀 마련',
      '민족사서 『대동사(大東史)』를 저술하고 신간회 안동지회장으로 민족유일당 운동 주도',
      '1982년 건국훈장 독립장 추서'
    ],
    writings: ['대동사(大東史)', '동산문집(東山文集)'],
    relics: ['안동 전주류씨 삼산고택(국가민속문화유산)', '협동학교 터'],
  },
  {
    id: 'ryu-jingeol',
    name: '류진걸',
    hanjaName: '柳震杰',
    pseudonym: '수애(水愛)',
    generation: 22,
    birthDeath: '1873 ~ 1955',
    branch: '수곡파',
    title: '수애당 건립, 향촌 교육자',
    category: 'scholar',
    summary: '수애당(水愛堂)을 건립하고 근대 전환기 수곡마을의 가통과 향촌 공동체를 지킨 인물. 일제강점기에도 전통 가옥 건축의 정수를 이어 수애당을 완성하고 후진 양성에 힘썼습니다.',
    achievements: [
      '1939년 안동 수애당(경북 문화유산자료)을 창건하여 전통 건축과 문중 문화 보존',
      '격변기 향촌 사회의 미풍양속과 교육을 장려하며 가문의 구심점 유지'
    ],
    relics: ['수애당 고택(경북 문화유산자료)'],
  },
  {
    id: 'ryu-rim',
    name: '류림',
    hanjaName: '柳林',
    courtesyName: '화영(華永)',
    pseudonym: '단주(旦洲)',
    generation: 21,
    birthDeath: '1894 ~ 1961',
    branch: '수곡파',
    title: '대한민국 임시정부 국무위원 (건국훈장 독립장)',
    category: 'patriot',
    summary: '대한민국 임시정부 국무위원을 역임한 거물 독립운동가이자 어문학자. 수곡리 무실마을 출신으로, 1910년 단지 혈서를 쓰고 만주 서로군정서에서 무장투쟁을 전개하였으며, 백범 김구 등과 함께 임시정부를 이끌었습니다.',
    achievements: [
      '1910년 손가락을 끊어 ‘충군애국(忠君愛國)’ 혈서를 쓰고 무장독립운동 투신',
      '만주 서로군정서 활동 및 아나키스트 독립운동 총본산 결성',
      '대한민국 임시정부 국무위원으로 조국 광복 쟁취에 결정적 공헌',
      '한글학자로서 『한글말본』 저술 및 민족어 보급',
      '1962년 건국훈장 독립장 추서'
    ],
    writings: ['한글말본', '깊더조선말본', '단주유고'],
    relics: ['독립기념관 어록비', '수곡리 생가 터'],
  },
  {
    id: 'ryu-wonsik',
    name: '류원식',
    hanjaName: '柳元植',
    pseudonym: '백하(白下)',
    generation: 21,
    birthDeath: '1890 ~ 1945',
    branch: '수곡파',
    title: '서로군정서 독립군 군자금 헌납 (건국훈장 애족장)',
    category: 'patriot',
    summary: '가문의 전 재산을 정리하여 만주로 망명한 노블레스 오블리주의 표상. 신흥무관학교 설립을 지원하고 서로군정서 독립군 부대에 거액의 군자금을 헌납하며 무장 항일투쟁의 병참선을 담당했습니다.',
    achievements: [
      '문중의 전답과 재산을 매각하여 만주 서간도 서로군정서 군자금 전액 헌납',
      '신흥무관학교 독립군 양성 자금 지원 및 임시정부 연락망 구축',
      '1990년 건국훈장 애족장 추서'
    ],
    relics: ['만주 서로군정서 군자금 영수증(실물 사료)', '건국훈장 서훈록'],
  },
  {
    id: 'ryu-bongsi',
    name: '류봉시',
    hanjaName: '柳鳳時',
    courtesyName: '순경(舜卿)',
    pseudonym: '삼가(三嘉)',
    generation: 13,
    birthDeath: '1686 ~ 1754',
    branch: '수곡파 (삼가문중)',
    title: '조선 후기 유학자, 삼가정 창건',
    category: 'scholar',
    summary: '삼산 류정원, 용와 류승현 선생과 함께 학문을 연마하며 무실마을의 정자 문화와 도학 가풍을 진작시킨 영조 대 학자입니다. 후손들이 그의 덕업을 기리기 위해 삼가정을 건립하였습니다.',
    achievements: [
      '무실마을 사림의 강학 공간이자 정자 건축미를 대변하는 삼가정(三嘉亭) 건립 계기 마련',
      '영조 연간 가문의 학풍 전승 및 향촌 교화 선도'
    ],
    relics: ['삼가정(경북 문화유산자료 제50호, 구미 일선리 이건)'],
  },
  {
    id: 'ryu-yeonbak',
    name: '류연박',
    hanjaName: '柳淵博',
    courtesyName: '여구(汝九)',
    pseudonym: '정와(靜窩)',
    generation: 20,
    birthDeath: '1844 ~ 1925',
    branch: '수곡파 (정재종가)',
    title: '정재 종손, 안동의진 의병, 파리장서 서명 유림',
    category: 'patriot',
    summary: '정재 류치명 선생의 종손으로, 1895년 을미의병 당시 안동의진에 참여하여 항일 투쟁을 전개하였고, 1919년 3·1운동 직후 유림 대표로서 파리강화회의에 독립을 청원한 파리장서(巴里長書)에 서명하여 가문의 3대 독립운동 시원을 열었습니다.',
    achievements: [
      '1895년 안동의진(安東義陣) 의병으로 참여하여 국권 수호 투쟁 전개',
      '1919년 유림 파리장서 독립청원 서명 참여',
      '정재 종가의 가훈과 선비 정신을 무장·평화 항일 투쟁으로 계승'
    ],
    relics: ['정재종택', '파리장서 서명록 사본'],
  },
  {
    id: 'ryu-siyeon',
    name: '류시연',
    hanjaName: '柳時淵',
    courtesyName: '치옥(致玉)',
    generation: 20,
    birthDeath: '1872 ~ 1914',
    branch: '수곡파',
    title: '산남의진 의병장, 항일 10년 결사항전 순국 (건국훈장 독립장)',
    category: 'patriot',
    summary: '구한말 영남 의병의 전설적인 맹장. 1906년 영천 산남의진(山南義陣)에 참가한 이래 안동·청송·영천·영덕 일대 낙동강 유역과 태백산맥에서 일제 군경과 10여 년간 결사항전을 벌이다 1914년 체포되어 대구감옥에서 사형 순국하였습니다.',
    achievements: [
      '1906년~1914년 영남 일대에서 일제 헌병대와 10년간 게릴라 결사항전 전개',
      '일제 경찰의 집요한 토벌 작전 속에서도 굴복하지 않고 끝까지 무장 투쟁 고수',
      '1914년 대구감옥에서 장렬히 교수형 순국',
      '1983년 건국훈장 독립장 추서'
    ],
    relics: ['독립기념관 산남의진 전적록', '건국훈장 독립장 서훈록'],
  },
  {
    id: 'ryu-dongsi',
    name: '류동시',
    hanjaName: '柳東蓍',
    courtesyName: '사구(士九)',
    generation: 21,
    birthDeath: '1886 ~ 1961',
    branch: '수곡파 (정재종가)',
    title: '임동 챗거리시장 만세운동 주도 (건국훈장 애족장)',
    category: 'patriot',
    summary: '류연박의 아들이자 정재 류치명의 증손자. 1919년 고종 황제의 인산(장례)에 참여한 뒤 독립선언서를 입수하여 귀향, 1919년 3월 21일 임동 챗거리시장(편항 장터)에서 500여 군중의 독립만세운동을 사전 기획하고 주도하다 체포되어 옥고를 치렀습니다.',
    achievements: [
      '1919년 3월 21일 안동 임동 챗거리 장터 500여 만세 시위를 사전 모의·주도',
      '임동 경찰주재소 습격 및 식민 통치 기관 마비 투쟁',
      '대구복심법원에서 징역 2년형을 선고받고 옥고를 치름',
      '1990년 건국훈장 애족장 추서'
    ],
    relics: ['임동 만세의거 기념비', '건국훈장 서훈록'],
  },
  {
    id: 'ryu-dongjeo',
    name: '류동저',
    hanjaName: '柳東著',
    generation: 21,
    birthDeath: '1892 ~ 1948',
    branch: '수곡파 (정재종가)',
    title: '신간회 안동지회, 독립군 군자금 지원 지사',
    category: 'patriot',
    summary: '류연박의 아들이자 류동시의 아우. 안동청년회 및 신간회 안동지회 간부로 활동하며, 만주 독립군 기지와 대한민국 임시정부에 가문의 전답을 매각한 비밀 독립운동 군자금을 지속적으로 조달하였습니다.',
    achievements: [
      '신간회 안동지회 및 안동청년회 결성 주도 및 민족 운동 전개',
      '정재 종가의 가산 지원을 통해 만주 무장투쟁 군자금 비밀 조달',
      '청년 계몽 및 향촌 자치 운동 헌신'
    ],
    relics: ['신간회 안동지회 명록', '정재종택 기록'],
  }
];

// 2. 계보 트리 데이터 (시조부터 수곡파 주요 계통)
export const GENEALOGY_TREE: GenealogyNode[] = [
  {
    id: "g-1",
    name: "류습 (柳濕)",
    hanjaName: "柳濕",
    generation: 1,
    branch: "전주류씨 중시조",
    title: "완산부원군(完山府院君), 참지정사",
    childrenIds: ["g-2-1", "g-2-2", "g-2-3", "g-2-4", "g-2-5"],
    note: "고려 말 중흥조. 다섯 아들(극서·극간·극삼·극송·극제)이 모두 문과에 급제하여 ‘오자급제(五子及第)’를 이룸",
    jokboCode: 84181,
    jokboBook: 1,
    jokboPage: 1,
    subBranchKey: "root",
  },
  {
    id: "g-2-1",
    name: "류극서 (柳克恕)",
    hanjaName: "柳克恕",
    generation: 2,
    branch: "회헌공파 (檜軒公派 파조)",
    title: "집현전 직제학, 증 이조판서",
    isSubBranchHead: true,
    fatherId: "g-1",
    childrenIds: ["g-3-1", "g-3-2"],
    note: "수곡파(무실류씨)의 직계 파조. 호 회헌(檜軒), 직제학 역임 후 영남 안동계통의 선대 개척",
    jokboCode: 84187,
    jokboBook: 1,
    jokboPage: 1,
    subBranchKey: "root",
  },
  {
    id: "g-2-2",
    name: "류극강 (柳克剛)",
    hanjaName: "柳克剛",
    generation: 2,
    branch: "부사공파",
    title: "양주부사",
    fatherId: "g-1",
    jokboCode: 84182,
    subBranchKey: "root",
  },
  {
    id: "g-2-3",
    name: "류극수 (柳克修)",
    hanjaName: "柳克修",
    generation: 2,
    branch: "밀직사공파",
    title: "밀직사 좌승지",
    fatherId: "g-1",
    jokboCode: 84326,
    subBranchKey: "root",
  },
  {
    id: "g-2-4",
    name: "류극제 (柳克濟)",
    hanjaName: "柳克濟",
    generation: 2,
    branch: "참판공파",
    title: "이조참판",
    fatherId: "g-1",
    jokboCode: 84374,
    subBranchKey: "root",
  },
  {
    id: "g-2-5",
    name: "류극거 (柳克渠)",
    hanjaName: "柳克渠",
    generation: 2,
    branch: "첨서공파",
    title: "첨서중추원사",
    fatherId: "g-1",
    jokboCode: 84386,
    subBranchKey: "root",
  },
  {
    id: "g-3-1",
    name: "류빈 (柳濱)",
    hanjaName: "柳濱",
    generation: 3,
    branch: "회헌공파 직계",
    title: "영흥부사",
    fatherId: "g-2-1",
    childrenIds: ["g-4-1", "g-4-2"],
    note: "경손·의손·신손·말손 4형제를 두어 문벌을 크게 융성시킴",
    jokboCode: 84250,
    jokboBook: 1,
    subBranchKey: "root",
  },
  {
    id: "g-3-2",
    name: "류정 (柳汀)",
    hanjaName: "柳汀",
    generation: 3,
    branch: "회헌공파 지파",
    fatherId: "g-2-1",
    jokboCode: 84188,
    subBranchKey: "root",
  },
  {
    id: "g-4-1",
    name: "류의손 (柳義孫)",
    hanjaName: "柳義孫",
    courtesyName: "효숙(孝叔)",
    pseudonym: "회헌(檜軒)",
    generation: 4,
    birthDeath: "1398 ~ 1450",
    branch: "회헌공파 직계",
    title: "집현전 부제학, 대제학, 대사헌, 예조참판",
    fatherId: "g-3-1",
    childrenIds: ["g-5-1"],
    note: "세종 대 훈민정음 창제 및 운서·예악 편찬 주도. 기양서당 세덕사(世德祠) 주벽 배향",
    jokboCode: 84279,
    jokboBook: 1,
    subBranchKey: "root",
  },
  {
    id: "g-4-2",
    name: "류경손 (柳敬孫)",
    hanjaName: "柳敬孫",
    generation: 4,
    branch: "회헌공파 지파",
    title: "판관",
    fatherId: "g-3-1",
    jokboCode: 84251,
    subBranchKey: "root",
  },
  {
    id: "g-5-1",
    name: "류계동 (柳季潼)",
    hanjaName: "柳季潼",
    generation: 5,
    branch: "회헌공파 직계",
    title: "사헌부 감찰",
    fatherId: "g-4-1",
    childrenIds: ["g-6-1"],
    jokboCode: 84280,
    jokboBook: 1,
    subBranchKey: "root",
  },
  {
    id: "g-6-1",
    name: "류식 (柳軾)",
    hanjaName: "柳軾",
    generation: 6,
    branch: "회헌공파 직계",
    title: "진천현감, 증 판결사",
    fatherId: "g-5-1",
    childrenIds: ["g-7-1"],
    jokboCode: 84281,
    jokboBook: 1,
    subBranchKey: "root",
  },
  {
    id: "g-7-1",
    name: "류윤선 (柳潤善)",
    hanjaName: "柳潤善",
    generation: 7,
    branch: "회헌공파 직계",
    title: "진사, 학덕으로 추앙",
    fatherId: "g-6-1",
    childrenIds: ["g-8-1"],
    jokboCode: 378492,
    jokboBook: 2,
    jokboPage: 324,
    subBranchKey: "root",
  },
  {
    id: "g-8-1",
    name: "류성 (柳城)",
    hanjaName: "柳城",
    courtesyName: "여중(汝中)",
    generation: 8,
    birthDeath: "1533 ~ 1560",
    branch: "수곡파 (무실 입향 시조)",
    title: "성균생원, 증 사헌부 집의",
    isSubBranchHead: true,
    fatherId: "g-7-1",
    childrenIds: ["g-9-1", "g-9-2"],
    note: "청계 김진의 사위이자 학봉 김성일의 자형으로 안동 임동면 수곡리(무실마을)에 처음 입향하여 500년 터전을 개척",
    jokboCode: 378493,
    jokboBook: 2,
    jokboPage: 324,
    subBranchKey: "root",
  },
  {
    id: "g-9-1",
    name: "류복기 (柳復起)",
    hanjaName: "柳復起",
    courtesyName: "경순(景純) / 자 성서(聖瑞)",
    pseudonym: "기봉(岐峯)",
    generation: 9,
    birthDeath: "1555 ~ 1617",
    branch: "수곡파 파조 (무실 중흥 파조)",
    title: "증 사헌부 지평, 임진왜란 예안의병장",
    isSubBranchHead: true,
    fatherId: "g-8-1",
    childrenIds: ["g-10-1", "g-10-2", "g-10-3", "g-10-4", "g-10-5", "g-10-6", "g-10-7"],
    note: "퇴계 정통 학맥 계승, 기양서당 창건. 칠잠(七潛) 일곱 아들을 두어 무실문중을 영남 대족으로 도약시킴",
    jokboCode: 378494,
    jokboBook: 2,
    jokboPage: 324,
    subBranchKey: "jongpa",
  },
  {
    id: "g-9-2",
    name: "류복립 (柳復立)",
    hanjaName: "柳復立",
    generation: 9,
    branch: "수곡파 진사공파",
    title: "진사",
    fatherId: "g-8-1",
    note: "기봉공의 아우",
    jokboCode: 388777,
    subBranchKey: "root",
  },
  {
    id: "g-10-1",
    name: "류우잠 (柳友潛)",
    hanjaName: "柳友潛",
    pseudonym: "취암(鷲巖)",
    generation: 10,
    branch: "수곡파 종파 (취암공파)",
    title: "통정대부",
    fatherId: "g-9-1",
    childrenIds: ["g-11-1", "g-11-2", "g-11-3", "g-11-4", "g-11-5"],
    note: "기봉공의 장자. 오목(五木: 숙·직·욱·학·격) 다섯 아들을 두어 무실 종통을 계승",
    jokboCode: 378495,
    jokboBook: 2,
    subBranchKey: "jongpa",
  },
  {
    id: "g-10-2",
    name: "류득잠 (柳得潛)",
    hanjaName: "柳得潛",
    generation: 10,
    branch: "수곡파 지파 (득잠공파)",
    fatherId: "g-9-1",
    note: "사위: 석문 정영방(鄭榮邦, 영양 두들마을 서석지 조성자)",
    jokboCode: 378587,
    subBranchKey: "chiljam",
  },
  {
    id: "g-10-3",
    name: "류지잠 (柳知潛)",
    hanjaName: "柳知潛",
    generation: 10,
    branch: "수곡파 지파 (지잠공파)",
    fatherId: "g-9-1",
    jokboCode: 378618,
    subBranchKey: "chiljam",
  },
  {
    id: "g-10-4",
    name: "류수잠 (柳守潛)",
    hanjaName: "柳守潛",
    generation: 10,
    branch: "수곡파 지파 (수잠공파)",
    fatherId: "g-9-1",
    jokboCode: 378661,
    subBranchKey: "chiljam",
  },
  {
    id: "g-10-5",
    name: "류의잠 (柳宜潛)",
    hanjaName: "柳宜潛",
    generation: 10,
    branch: "수곡파 지파 (의잠공파)",
    fatherId: "g-9-1",
    jokboCode: 378681,
    subBranchKey: "chiljam",
  },
  {
    id: "g-10-6",
    name: "류희잠 (柳希潛)",
    hanjaName: "柳希潛",
    generation: 10,
    branch: "수곡파 지파 (희잠공파)",
    fatherId: "g-9-1",
    jokboCode: 378744,
    subBranchKey: "chiljam",
  },
  {
    id: "g-10-7",
    name: "류시잠 (柳時潛)",
    hanjaName: "柳時潛",
    generation: 10,
    branch: "수곡파 지파 (시잠공파)",
    fatherId: "g-9-1",
    jokboCode: 378792,
    subBranchKey: "chiljam",
  },
  {
    id: "g-11-1",
    name: "류숙 (柳橚)",
    hanjaName: "柳橚",
    generation: 11,
    branch: "수곡파 종파",
    title: "학행으로 추앙",
    fatherId: "g-10-1",
    childrenIds: ["g-12-1", "g-12-2", "g-12-3"],
    note: "진휘(정재계)·익휘(삼산계)·정휘(동암계)를 두어 수곡파 3대 학파의 공동 직계 선조가 됨",
    jokboCode: 378496,
    jokboBook: 2,
    subBranchKey: "jongpa",
  },
  {
    id: "g-11-2",
    name: "류직 (柳㮨)",
    hanjaName: "柳㮨",
    generation: 11,
    branch: "수곡파 오목 지파",
    fatherId: "g-10-1",
    jokboCode: 378528,
    subBranchKey: "chiljam",
  },
  {
    id: "g-11-3",
    name: "류욱 (柳㮋)",
    hanjaName: "柳㮋",
    generation: 11,
    branch: "수곡파 오목 지파",
    fatherId: "g-10-1",
    jokboCode: 378537,
    subBranchKey: "chiljam",
  },
  {
    id: "g-11-4",
    name: "류학 (柳㰒)",
    hanjaName: "柳㰒",
    generation: 11,
    branch: "수곡파 오목 지파",
    fatherId: "g-10-1",
    jokboCode: 378553,
    subBranchKey: "chiljam",
  },
  {
    id: "g-11-5",
    name: "류격 (柳格)",
    hanjaName: "柳格",
    generation: 11,
    branch: "수곡파 오목 지파",
    fatherId: "g-10-1",
    jokboCode: 378568,
    subBranchKey: "chiljam",
  },
  {
    id: "g-12-1",
    name: "류진휘 (柳振輝)",
    hanjaName: "柳振輝",
    generation: 12,
    branch: "수곡파 무실종택계 (정재종택)",
    title: "유학자",
    fatherId: "g-11-1",
    childrenIds: ["g-13-1", "g-13-2"],
    jokboCode: 378497,
    subBranchKey: "jongpa",
  },
  {
    id: "g-12-2",
    name: "류익휘 (柳益輝)",
    hanjaName: "柳益輝",
    generation: 12,
    branch: "수곡파 삼산파",
    title: "유학자",
    fatherId: "g-11-1",
    childrenIds: ["g-13-3"],
    jokboCode: 378516,
    subBranchKey: "samsan",
  },
  {
    id: "g-12-3",
    name: "류정휘 (柳挺輝)",
    hanjaName: "柳挺輝",
    generation: 12,
    branch: "수곡파 동암파",
    title: "유학자",
    fatherId: "g-11-1",
    childrenIds: ["g-13-4"],
    jokboCode: 378503,
    subBranchKey: "dongam",
  },
  {
    id: "g-13-1",
    name: "류봉시 (柳奉時)",
    hanjaName: "柳奉時",
    courtesyName: "자 우도(于道)",
    pseudonym: "송월헌(松月軒)",
    generation: 13,
    birthDeath: "1654 ~ 1709",
    branch: "수곡파 무실종택계 (정재종택)",
    title: "학덕으로 추앙, 삼가정(三可亭) 창건자",
    fatherId: "g-12-1",
    childrenIds: ["g-14-1", "g-14-2"],
    note: "부모 봉양의 효행으로 삼가정을 짓고 도학을 연마함",
    jokboCode: 379003,
    subBranchKey: "jongpa",
  },
  {
    id: "g-13-2",
    name: "류종시 (柳宗時)",
    hanjaName: "柳宗時",
    generation: 13,
    branch: "수곡파 백하공계",
    fatherId: "g-12-1",
    childrenIds: ["g-14-3"],
    jokboCode: 378820,
    subBranchKey: "jongpa",
  },
  {
    id: "g-13-3",
    name: "류상시 (柳相時)",
    hanjaName: "柳相時",
    generation: 13,
    branch: "수곡파 삼산파",
    fatherId: "g-12-2",
    childrenIds: ["g-14-4"],
    jokboCode: 379542,
    subBranchKey: "samsan",
  },
  {
    id: "g-13-4",
    name: "류창시 (柳昌時)",
    hanjaName: "柳昌時",
    generation: 13,
    branch: "수곡파 동암파",
    fatherId: "g-12-3",
    childrenIds: ["g-14-5"],
    jokboCode: 379211,
    subBranchKey: "dongam",
  },
  {
    id: "g-14-1",
    name: "류승현 (柳升鉉)",
    hanjaName: "柳升鉉",
    generation: 14,
    branch: "수곡파 호암공계",
    title: "유학자",
    fatherId: "g-13-1",
    childrenIds: ["g-15-1"],
    jokboCode: 379004,
    subBranchKey: "jongpa",
  },
  {
    id: "g-14-2",
    name: "류관현 (柳觀鉉)",
    hanjaName: "柳觀鉉",
    generation: 14,
    branch: "수곡파 정재종택 직계",
    fatherId: "g-13-1",
    childrenIds: ["g-15-2"],
    jokboCode: 379093,
    subBranchKey: "jongpa",
  },
  {
    id: "g-14-3",
    name: "류창현 (柳昌鉉)",
    hanjaName: "柳昌鉉",
    generation: 14,
    branch: "수곡파 백하공계",
    fatherId: "g-13-2",
    childrenIds: ["g-15-3"],
    jokboCode: 378869,
    subBranchKey: "jongpa",
  },
  {
    id: "g-14-4",
    name: "류석구 (柳錫龜)",
    hanjaName: "柳錫龜",
    generation: 14,
    branch: "수곡파 삼산파",
    fatherId: "g-13-3",
    childrenIds: ["g-15-4"],
    jokboCode: 379543,
    subBranchKey: "samsan",
  },
  {
    id: "g-14-5",
    name: "류신적 (柳信迪)",
    hanjaName: "柳信迪",
    generation: 14,
    branch: "수곡파 동암파",
    fatherId: "g-13-4",
    childrenIds: ["g-15-5"],
    jokboCode: 379212,
    subBranchKey: "dongam",
  },
  {
    id: "g-15-1",
    name: "류도원 (柳道源)",
    hanjaName: "柳道源",
    courtesyName: "자 도백(道伯)",
    pseudonym: "호암(壺巖) / 도헌(陶軒)",
    generation: 15,
    birthDeath: "1721 ~ 1791",
    branch: "수곡파 호암공계",
    title: "유학자, 『호암집』 찬술",
    fatherId: "g-14-1",
    childrenIds: ["g-16-1", "g-16-2"],
    jokboCode: 379005,
    subBranchKey: "jongpa",
  },
  {
    id: "g-15-2",
    name: "류통원 (柳通源)",
    hanjaName: "柳通源",
    generation: 15,
    branch: "수곡파 정재종택계",
    fatherId: "g-14-2",
    childrenIds: ["g-16-3"],
    jokboCode: 379094,
    subBranchKey: "jongpa",
  },
  {
    id: "g-15-3",
    name: "류세택 (柳世澤)",
    hanjaName: "柳世澤",
    generation: 15,
    branch: "수곡파 백하공계",
    fatherId: "g-14-3",
    childrenIds: ["g-16-4"],
    jokboCode: 378870,
    subBranchKey: "jongpa",
  },
  {
    id: "g-15-4",
    name: "류정원 (柳正源)",
    hanjaName: "柳正源",
    courtesyName: "자 순백(淳伯)",
    pseudonym: "삼산(三山)",
    generation: 15,
    birthDeath: "1687 ~ 1761",
    branch: "수곡파 삼산파 중흥조",
    title: "사헌부 대사헌, 이조참판, 대제학",
    isSubBranchHead: true,
    fatherId: "g-14-4",
    childrenIds: ["g-16-5"],
    note: "『삼산집』 저술. 영조 대 탕평의 한계를 비판하고 도학 정치를 주창한 영남 유학의 거목",
    jokboCode: 379544,
    subBranchKey: "samsan",
  },
  {
    id: "g-15-5",
    name: "류장원 (柳長源)",
    hanjaName: "柳長源",
    courtesyName: "자 숙원(叔遠)",
    pseudonym: "동암(東巖)",
    generation: 15,
    birthDeath: "1724 ~ 1796",
    branch: "수곡파 동암파 파조",
    title: "유학자, 『상변통고』 찬술자",
    isSubBranchHead: true,
    fatherId: "g-14-5",
    childrenIds: ["g-16-6"],
    note: "유네스코 세계기록유산 『상변통고(常變通攷)』 22권 11책을 집대성하여 조선 예학의 표준을 확립",
    jokboCode: 379213,
    subBranchKey: "dongam",
  },
  {
    id: "g-16-1",
    name: "류범휴 (柳範休)",
    hanjaName: "柳範休",
    courtesyName: "자 천서(天瑞)",
    pseudonym: "호곡(壺谷)",
    generation: 16,
    birthDeath: "1744 ~ 1823",
    branch: "수곡파 호암공계",
    title: "사헌부 장령, 『호곡집』 찬술",
    fatherId: "g-15-1",
    note: "퇴계학맥과 성호 이익의 근기실학을 융합한 도학자",
    jokboCode: 379006,
    subBranchKey: "jongpa",
  },
  {
    id: "g-16-2",
    name: "류낙휴 (柳洛休)",
    hanjaName: "柳洛休",
    courtesyName: "자 주서(疇瑞)",
    pseudonym: "표항(瓢巷)",
    generation: 16,
    branch: "수곡파 호암공계",
    fatherId: "g-15-1",
    jokboCode: 379043,
    subBranchKey: "jongpa",
  },
  {
    id: "g-16-3",
    name: "류성휴 (柳星休)",
    hanjaName: "柳星休",
    generation: 16,
    branch: "수곡파 정재종택계",
    fatherId: "g-15-2",
    childrenIds: ["g-17-1"],
    jokboCode: 379095,
    subBranchKey: "jongpa",
  },
  {
    id: "g-16-4",
    name: "류복휴 (柳復休)",
    hanjaName: "柳復休",
    generation: 16,
    branch: "수곡파 백하공계",
    fatherId: "g-15-3",
    childrenIds: ["g-17-2"],
    jokboCode: 378878,
    subBranchKey: "jongpa",
  },
  {
    id: "g-16-5",
    name: "류일휴 (柳日休)",
    hanjaName: "柳日休",
    generation: 16,
    branch: "수곡파 삼산파",
    fatherId: "g-15-4",
    childrenIds: ["g-17-3"],
    jokboCode: 379596,
    subBranchKey: "samsan",
  },
  {
    id: "g-16-6",
    name: "류천휴 (柳川休)",
    hanjaName: "柳川休",
    generation: 16,
    branch: "수곡파 동암파",
    fatherId: "g-15-5",
    childrenIds: ["g-17-4"],
    jokboCode: 379214,
    subBranchKey: "dongam",
  },
  {
    id: "g-17-1",
    name: "류회문 (柳晦文)",
    hanjaName: "柳晦文",
    generation: 17,
    branch: "수곡파 정재종택계",
    fatherId: "g-16-3",
    childrenIds: ["g-18-1"],
    jokboCode: 379096,
    subBranchKey: "jongpa",
  },
  {
    id: "g-17-2",
    name: "류적문 (柳迪文)",
    hanjaName: "柳迪文",
    generation: 17,
    branch: "수곡파 백하공계",
    fatherId: "g-16-4",
    childrenIds: ["g-18-2"],
    jokboCode: 378894,
    subBranchKey: "jongpa",
  },
  {
    id: "g-17-3",
    name: "류기문 (柳器文)",
    hanjaName: "柳器文",
    generation: 17,
    branch: "수곡파 삼산파",
    fatherId: "g-16-5",
    childrenIds: ["g-18-3"],
    jokboCode: 379608,
    subBranchKey: "samsan",
  },
  {
    id: "g-17-4",
    name: "류약문 (柳約文)",
    hanjaName: "柳約文",
    generation: 17,
    branch: "수곡파 동암파",
    fatherId: "g-16-6",
    childrenIds: ["g-18-4"],
    jokboCode: 379236,
    subBranchKey: "dongam",
  },
  {
    id: "g-18-1",
    name: "류치명 (柳致明)",
    hanjaName: "柳致明",
    courtesyName: "자 성백(誠伯)",
    pseudonym: "정재(定齋)",
    generation: 18,
    birthDeath: "1777 ~ 1861",
    branch: "수곡파 정재종택 파조",
    title: "사헌부 대사헌, 이조참판, 도학 영남 유종",
    isSubBranchHead: true,
    fatherId: "g-17-1",
    childrenIds: ["g-19-1"],
    note: "퇴계 학통의 정맥을 이은 조선 후기 영남 유림의 영수. 안동 무실 정재종택의 중흥조",
    jokboCode: 379097,
    subBranchKey: "jongpa",
  },
  {
    id: "g-18-2",
    name: "류치경 (柳致敬)",
    hanjaName: "柳致敬",
    generation: 18,
    branch: "수곡파 백하공계",
    fatherId: "g-17-2",
    childrenIds: ["g-19-2"],
    jokboCode: 378895,
    subBranchKey: "jongpa",
  },
  {
    id: "g-18-3",
    name: "류치형 (柳致馨)",
    hanjaName: "柳致馨",
    generation: 18,
    branch: "수곡파 삼산파",
    fatherId: "g-17-3",
    childrenIds: ["g-19-3"],
    jokboCode: 379609,
    subBranchKey: "samsan",
  },
  {
    id: "g-18-4",
    name: "류치준 (柳致儁)",
    hanjaName: "柳致儁",
    generation: 18,
    branch: "수곡파 동암파",
    fatherId: "g-17-4",
    childrenIds: ["g-19-4"],
    jokboCode: 379237,
    subBranchKey: "dongam",
  },
  {
    id: "g-19-1",
    name: "류지호 (柳止鎬)",
    hanjaName: "柳止鎬",
    generation: 19,
    branch: "수곡파 정재종택계",
    title: "유학자",
    fatherId: "g-18-1",
    childrenIds: ["g-20-1"],
    jokboCode: 389491,
    subBranchKey: "jongpa",
  },
  {
    id: "g-19-2",
    name: "류학호 (柳學鎬)",
    hanjaName: "柳學鎬",
    generation: 19,
    branch: "수곡파 백하공계",
    fatherId: "g-18-2",
    childrenIds: ["g-20-2"],
    jokboCode: 383280,
    subBranchKey: "jongpa",
  },
  {
    id: "g-19-3",
    name: "류정진 (柳定鎭)",
    hanjaName: "柳定鎭",
    generation: 19,
    branch: "수곡파 삼산파",
    fatherId: "g-18-3",
    childrenIds: ["g-20-3"],
    jokboCode: 392273,
    subBranchKey: "samsan",
  },
  {
    id: "g-19-4",
    name: "류정호 (柳正鎬)",
    hanjaName: "柳正鎬",
    generation: 19,
    branch: "수곡파 동암파",
    fatherId: "g-18-4",
    childrenIds: ["g-20-4"],
    jokboCode: 390294,
    subBranchKey: "dongam",
  },
  {
    id: "g-20-1",
    name: "류연박 (柳淵博)",
    hanjaName: "柳淵博",
    generation: 20,
    birthDeath: "1868 ~ 1928",
    branch: "수곡파 정재종택계 (독립운동 가문)",
    title: "애국지사 (대통령표창)",
    fatherId: "g-19-1",
    childrenIds: ["g-21-1", "g-21-2"],
    note: "정재 류치명의 종손. 1919년 3·1운동 직후 유림의 파리장서 독립청원 운동에 적극 참여하고 군자금을 조달함",
    jokboCode: 389492,
    subBranchKey: "jongpa",
  },
  {
    id: "g-20-2",
    name: "류연윤 (柳淵潤)",
    hanjaName: "柳淵潤",
    generation: 20,
    branch: "수곡파 백하공계",
    fatherId: "g-19-2",
    childrenIds: ["g-21-3"],
    jokboCode: 383323,
    subBranchKey: "jongpa",
  },
  {
    id: "g-20-3",
    name: "류필영 (柳必永)",
    hanjaName: "柳必永",
    courtesyName: "자 치화(稚華)",
    pseudonym: "서산(西山)",
    generation: 20,
    birthDeath: "1841 ~ 1924",
    branch: "수곡파 삼산파",
    title: "영남 유림수선, 파리장서 독립청원 서명 애국지사",
    fatherId: "g-19-3",
    childrenIds: ["g-21-4"],
    note: "1919년 파리강화회의에 조국 독립을 청원한 영남 137인 유림 대표 서명자. 『서산집』 저술",
    jokboCode: 392274,
    subBranchKey: "samsan",
  },
  {
    id: "g-20-4",
    name: "류시연 (柳時淵)",
    hanjaName: "柳時淵",
    courtesyName: "자 성징(聖徵)",
    pseudonym: "우헌(愚軒)",
    generation: 20,
    birthDeath: "1872 ~ 1914",
    branch: "수곡파 동암파",
    title: "산남의진(山南義陣) 영남 항일 의병장 (건국훈장 독립장)",
    fatherId: "g-19-4",
    note: "정미의병 당시 산남의진 중군장 및 소모장으로 영천·청송·포항 일대에서 일본군과 결사 항전",
    jokboCode: 390295,
    subBranchKey: "dongam",
  },
  {
    id: "g-21-1",
    name: "류동시 (柳東蓍)",
    hanjaName: "柳東蓍",
    generation: 21,
    birthDeath: "1896 ~ 1941",
    branch: "수곡파 정재종택계 (3대 독립투쟁)",
    title: "애국지사 (건국훈장 애족장)",
    fatherId: "g-20-1",
    note: "류연박의 장남. 만주 정의부(正義府)와 의열투쟁, 신간회 안동지회 청년운동 주도",
    jokboCode: 389493,
    subBranchKey: "jongpa",
  },
  {
    id: "g-21-2",
    name: "류동저 (柳東著)",
    hanjaName: "柳東著",
    generation: 21,
    branch: "수곡파 정재종택계 (3대 독립투쟁)",
    title: "신간회 안동지회, 독립운동 군자금 조달",
    fatherId: "g-20-1",
    note: "류연박의 차남. 안동청년회 및 가산 전답을 처분하여 만주 독립군 기지에 군자금 지원",
    jokboCode: 389538,
    subBranchKey: "jongpa",
  },
  {
    id: "g-21-3",
    name: "류원식 (柳元植)",
    hanjaName: "柳元植",
    courtesyName: "자 원백(元伯)",
    pseudonym: "백하(白下)",
    generation: 21,
    birthDeath: "1888 ~ 1944",
    branch: "수곡파 백하공계",
    title: "만주 서로군정서·신흥무관학교 지원 애국지사 (건국훈장 애족장)",
    fatherId: "g-20-2",
    note: "만주 서간도로 망명하여 전 재산을 독립군 군자금으로 헌납하고 무장 항일투쟁 헌신",
    jokboCode: 383324,
    subBranchKey: "jongpa",
  },
  {
    id: "g-21-4",
    name: "류흥식 (柳興植)",
    hanjaName: "柳興植",
    generation: 21,
    birthDeath: "1884 ~ 1957",
    branch: "수곡파 삼산파",
    title: "파리장서 및 영남 유림 항일운동가",
    fatherId: "g-20-3",
    note: "서산 류필영 선생의 뜻을 이어 조국 광복과 가학 전승에 헌신",
    jokboCode: 392329,
    subBranchKey: "samsan",
  },
];

// 3. 기록물(아카이브) 데이터
export const ARCHIVE_ITEMS: ArchiveItem[] = [
  {
    id: 'arch-sangbyeon-tonggo',
    title: '『상변통고(常變通攷)』 목판 (유네스코 세계기록유산)',
    hanjaTitle: '常變通攷 木板 (UNESCO 世界記錄遺産)',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 정조 7년 (1783년 찬술, 1830년대 판각)',
    location: '한국국학진흥원 장판각 (유교책판)',
    imageUrl: '/images/archives/sangbyeon_tonggo.jpg',
    description: '동암(東巖) 류장원(柳長源, 1724~1796) 선생이 한강 정구의 『오선생예설분류』 등을 보완하여 조선 유학 예학(禮學)의 모든 쟁점과 의례 절차를 집대성한 22권 11책의 기념비적 예서 목판입니다. 2015년 유네스코 세계기록유산으로 등재된 한국의 유교책판 중 대표적인 저작입니다.',
    significance: '조선 후기 예학의 최고 표준서로 공인받아 중앙과 영남 사림의 전례 논쟁을 정리한 1급 학술 기록유산입니다.',
    tag: ['상변통고', '유네스코', '세계기록유산', '동암 류장원', '한국국학진흥원', '예학'],
    sourceOrKeeper: '한국국학진흥원 장판각 기탁'
  },
  {
    id: 'arch-samsan-jib',
    title: '삼산집(三山集) 목판본 및 필사본',
    hanjaTitle: '三山集 木板本 및 筆寫本',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 정조 연간 (1700년대 후반)',
    location: '한국국학진흥원 기탁 보관',
    imageUrl: '/images/archives/samsan_jib.jpg',
    description: '대사헌 삼산 류정원(1687~1761)의 시문과 소(疏), 서(書), 잡저 등을 집대성한 문집. 영조 대 붕당의 폐해를 바로잡으려는 강직한 상소문과 퇴계 학통을 심화시킨 성리설이 망라되어 있습니다.',
    significance: '영남 유학과 조선 후기 정치사·사상사를 이해하는 데 있어 필수불가결한 1급 사료입니다.',
    tag: ['문집', '삼산 류정원', '한국국학진흥원', '영남학파'],
    sourceOrKeeper: '전주류씨 수곡파 종중 / 국학진흥원'
  },
  {
    id: 'arch-gibong-jib',
    title: '『기봉집(岐峯集)』 목판 및 초간본',
    hanjaTitle: '岐峯集 木板 및 初刊本',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 현종 연간 (1660년대 판각 간행)',
    location: '한국국학진흥원 기탁 보관',
    imageUrl: '/images/archives/gibong_jib.jpg',
    description: '임진왜란 예안의병장 기봉 류복기(1555~1617) 선생의 시문과 의병 활동 격문, 안동 선비들과 주고받은 서간 등을 수록한 문집 목판입니다. 한강 정구와 여헌 장현광 등 당대 석학들이 선생의 충절과 행적을 상찬한 서문이 수록되어 있습니다.',
    significance: '임진왜란 초기 영남 북부지역 의병 창의와 낙동강 방어전의 실상을 실증하는 국방·전쟁사 1차 사료입니다.',
    tag: ['기봉집', '기봉 류복기', '예안의병', '임진왜란', '한국국학진흥원'],
    sourceOrKeeper: '전주류씨 기봉문중 / 국학진흥원'
  },
  {
    id: 'arch-musil-jongtaek',
    title: '전주류씨 수곡파 무실종택(水谷宗宅)',
    hanjaTitle: '全州柳氏 水谷派 務實宗宅',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '16세기 중엽 창건 (1988년 수몰지구 해체 이건)',
    location: '경상북도 안동시 임동면 수곡용계로 402',
    imageUrl: '/images/archives/musil_jongtaek.jpg',
    description: '수곡파의 입향조 류성과 기봉 류복기 이래 400여 년간 무실마을의 구심점 역할을 해온 대종택입니다. 안동 지방 양반 가옥의 전형적인 □자형 배치 구조를 간직하고 있으며, 댐 건설 당시 원형 그대로 고지대로 이건되었습니다.',
    significance: '경상북도 민속문화유산 제47호로 지정되어, 수몰의 수난 속에서도 가문의 맥과 건축 양식을 온전히 지켜낸 상징적 유적입니다.',
    tag: ['무실종택', '수곡종택', '민속문화유산', '종택건축', '이건'],
    sourceOrKeeper: '경상북도 민속문화유산 (수곡파 대종회 관리)'
  },
  {
    id: 'arch-gibong-jeongsa',
    title: '기봉정사(岐峯精舍) 전경 및 상량문',
    hanjaTitle: '岐峯精舍 全景 및 上樑文',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 선조~인조 (1600년대 초 건립, 1975년 이건)',
    location: '경상북도 안동시 임동면 수곡용계로',
    imageUrl: '/images/archives/gibong_jeongsa.jpg',
    description: '임진왜란 예안 의병장 기봉 류복기 선생의 덕업을 기리기 위해 건립된 정사. 본래 안동군 임동면 수곡리 무실마을 중심부에 위치하였으나, 안동댐 건설로 수몰 위기에 처하자 현재의 고지대로 해체 이건되었습니다.',
    significance: '수곡파의 시원(始原)이자 안동 사림의 의병 정신을 상징하는 대표적 건축 문화유산입니다.',
    tag: ['기봉정사', '임진왜란', '의병', '안동댐 이건'],
    sourceOrKeeper: '경상북도 문화유산자료'
  },
  {
    id: 'arch-giyang-seodang',
    title: '기양서당(岐陽書堂)과 세덕사(世德祠)',
    hanjaTitle: '岐陽書堂 및 世德祠',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '1615년 창건, 1716년 중건 (1988년 이건)',
    location: '경상북도 안동시 임동면 수곡용계로 400',
    imageUrl: '/images/archives/giyang_seodang.jpg',
    description: '기봉 류복기 선생이 후학을 훈도하기 위해 세운 서재에서 비롯된 서당입니다. 경내의 세덕사에는 고려 말 조선 초의 명신 회헌(檜軒) 류의손과 기봉 류복기 선생의 위패를 봉안하여 춘추로 향사를 봉행합니다.',
    significance: '경상북도 민속문화유산으로 지정된 문중 서당으로, 수곡파 문중 교육과 제향의 핵심 공간입니다.',
    tag: ['기양서당', '세덕사', '회헌 류의손', '기봉 류복기', '민속문화유산'],
    sourceOrKeeper: '경상북도 민속문화유산'
  },
  {
    id: 'arch-suaedang',
    title: '수애당(水愛堂) 고택',
    hanjaTitle: '水愛堂 古宅',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '1939년 건립 (조선 후기 사대부 양식 계승)',
    location: '경상북도 안동시 임동면 수곡용계로 429',
    imageUrl: '/images/archives/suaedang.jpg',
    description: '수애 류진걸(柳震杰) 선생이 건립한 전통 가옥으로, 3간 겹집 구조와 정교한 목조 가구 기법이 돋보입니다. 수곡리 수몰 직전 현재 위치로 옮겨 세웠으며, 고택 체험과 문중 학술 모임 공간으로 널리 활용되고 있습니다.',
    significance: '경상북도 문화유산자료로 지정되어, 근대 전환기 안동 사대부 가옥의 건축사적 진화와 수몰 극복사를 증명합니다.',
    tag: ['수애당', '류진걸', '문화유산자료', '전통고택'],
    sourceOrKeeper: '경상북도 문화유산자료'
  },
  {
    id: 'arch-samsanjeong',
    title: '삼산정(三山亭)과 편액 유묵',
    hanjaTitle: '三山亭 扁額 및 遺墨',
    category: 'calligraphy',
    categoryLabel: '유묵·현판',
    dateOrEra: '조선 영조 44년 (1768년 건립)',
    location: '경상북도 안동시 임동면',
    imageUrl: '/images/archives/samsanjeong.jpg',
    description: '삼산 류정원 선생의 학덕을 추모하기 위해 후학들과 문중이 세운 정자. 정자 내에 걸린 삼산정 편액과 제영록은 당대 명필과 영남 유학 거두들의 필적이 온전히 보존되어 있습니다.',
    significance: '경상북도 유형문화유산으로 지정되어 조선 후기 정자 건축미와 서예 예술의 정수를 보여줍니다.',
    tag: ['삼산정', '현판', '서예', '유형문화유산'],
    sourceOrKeeper: '전주류씨 삼산문중'
  },
  {
    id: 'arch-submerged-musil',
    title: '수몰 전 무실마을(수곡리) 전경 사진',
    hanjaTitle: '水谷里(水室) 水沒前 全景 寫眞',
    category: 'submerged_history',
    categoryLabel: '수몰사 기록',
    dateOrEra: '1980년대 (임하댐 수몰 전)',
    location: '경북 안동시 임동면 수곡리 (구 수곡동 본마을)',
    imageUrl: '/images/archives/submerged_musil.jpg',
    description: '임하댐 건설로 마을 전역이 물속에 잠기기 전, 400여 년간 전주류씨 집성촌을 이루었던 무실마을(수곡리)의 실제 원경 기록 사진입니다. 마을 뒤편의 아기산과 유유히 흐르던 강줄기, 그리고 무실종택을 비롯한 고택들이 옹기종기 자리 잡았던 본래의 마을 풍경을 생생히 보여줍니다. (사진 제공: 류경림)',
    significance: '댐 건설로 수장되어 물리적으로 사라진 본향의 원형과 가문의 터전을 증명하는 대체 불가능한 1차 시각 기록유산입니다.',
    tag: ['수몰마을', '무실마을', '수곡리', '임하댐', '경북기록문화연구원', '고향'],
    sourceOrKeeper: '(사)경북기록문화연구원 사진아카이브 (P20180000006663)'
  },
  {
    id: 'arch-submerged-survey-map',
    title: '1974년 안동댐 수몰지구 문화재 지표조사도 및 마을 실측도',
    hanjaTitle: '1974年 安東댐 水沒地區 實測圖',
    category: 'submerged_history',
    categoryLabel: '수몰사 기록',
    dateOrEra: '1974년 ~ 1975년',
    location: '문화재청(국가유산청) 국립문화유산연구원 아카이브',
    imageUrl: '/images/archives/submerged_survey_map.jpg',
    description: '안동댐 담수를 앞두고 무실마을(수곡리) 전역의 고택 배치, 사당, 정자, 수목, 골목길의 위치를 정밀 실측한 도면 및 보고서입니다. 물에 잠기기 전 마을의 공간 구조와 가구별 소유 현황이 기록되어 있습니다.',
    significance: '수몰된 집성촌의 원형 지형과 공간 배치를 디지털 공간에 3D로 복원할 수 있는 결정적 기준 좌표 자료입니다.',
    tag: ['수몰지표조사', '마을실측도', '안동댐', '지적도', '디지털복원'],
    sourceOrKeeper: '영남 종택 소장 고지도 실물 (국가유산포털)'
  },
  {
    id: 'arch-paris-petition',
    title: '파리장서(巴里長書) 독립청원 서산 류필영 서명록',
    hanjaTitle: '巴里長書 獨立請願書 署名錄',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '1919년 (대한민국 임시정부 원년)',
    location: '독립기념관 소장 자료 연계',
    imageUrl: '/images/archives/paris_petition.jpg',
    description: '1919년 김복한, 곽종석 등 영호남 유림 137인이 파리강화회의에 조국의 독립을 정식 청원한 국한문 독립선언서. 수곡파의 거유 서산 류필영 선생이 목숨을 걸고 서명에 동참하였습니다.',
    significance: '전통 유림 가문이 망국의 위기에서 근대적 민족 독립운동으로 전환했음을 입증하는 역사적 쾌거입니다.',
    tag: ['독립운동', '파리장서', '서산 류필영', '3·1운동'],
    sourceOrKeeper: '국가등록문화유산 제664호 독립선언서 실물 원본'
  },
  {
    id: 'arch-baekha-independence',
    title: '백하 류원식 만주 서로군정서 독립투쟁 군자금 영수증 및 서한',
    hanjaTitle: '白下 柳元植 西路軍政署 軍資金 領收證',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '1910년대~1920년대',
    location: '독립기념관 독립운동사 자료집',
    imageUrl: '/images/archives/baekha_independence.jpg',
    description: '수곡파 16세손 백하 류원식 선생이 만주 서간도로 망명하여 신흥무관학교 건립 지원 및 서로군정서 독립군 부대에 문중 전답 매각 대금을 군자금으로 헌납한 내역과 임시정부 연계 비밀 통신문입니다.',
    significance: '영남의 전통 종가 가문이 노블레스 오블리주를 발휘하여 전 재산을 항일 무장투쟁에 바쳤음을 입증하는 독립운동 사료입니다.',
    tag: ['백하 류원식', '서로군정서', '신흥무관학교', '독립기념관', '애족장'],
    sourceOrKeeper: '국가등록문화유산 독립군 성립 서명문 실물'
  },
  {
    id: 'arch-genealogy-woodblocks',
    title: '전주류씨 수곡파 세보(世譜) 목판 및 정본',
    hanjaTitle: '全州柳氏 水谷派 世譜 木板',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 순조 및 고종 연간',
    location: '문중 장판각 보관',
    imageUrl: '/images/archives/genealogy_woodblocks.jpg',
    description: '기봉 류복기 선생 이하 수곡파 후손들의 계통을 상세히 수록한 족보 목판본. 자손들의 관직, 혼인 관계, 묘소 위치 등이 실증적으로 기록되어 있습니다.',
    significance: '한국 족보 문화의 전형이자 가문의 혈통적 정체성을 규명하는 1차 사료입니다.',
    tag: ['족보', '세보', '목판', '계보'],
    sourceOrKeeper: '수곡파 종중 대종회'
  },
  {
    id: 'arch-partition-deed',
    title: '수곡파 가계 분재기(分財記) 및 화회문기(和會文記)',
    hanjaTitle: '水谷派 家系 分財記 및 和會文記',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 숙종~영조 연간 (17~18세기)',
    location: '한국국학진흥원 수곡종택 기탁 고문서군',
    imageUrl: '/images/archives/partition_deed.jpg',
    description: '수곡파 종가에서 대대로 내려온 재산 분급 및 형제자매 간 합의 상속 기록 문서입니다. 전답, 가옥, 노비 등의 분배 내역과 서압(수결)이 고스란히 남아 있어 균분상속에서 적장자 우대 상속으로 이행하는 조선 후기 가족제도의 변화를 생생히 보여줍니다.',
    significance: '조선 후기 사회경제사 및 법제사, 영남 사림 가문의 가계 운영 방식을 연구하는 핵심 고문서입니다.',
    tag: ['분재기', '화회문기', '고문서', '한국국학진흥원', '사회경제사'],
    sourceOrKeeper: '한국국학진흥원 고문서 DB'
  },
  {
    id: 'arch-yean-righteous-army',
    title: '『예안의병일기(禮安義兵日記)』 및 창의격문',
    hanjaTitle: '禮安義兵日記 및 倡義檄文',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '선조 25년 (1592년 임진왜란)',
    location: '국립중앙도서관 및 문중 필사본 전승',
    imageUrl: '/images/archives/yean_righteous_army.jpg',
    description: '임진왜란 발발 직후 기봉 류복기와 동생 류복립 등이 예안 및 안동 유림들과 함께 의병을 창의하며 작성한 통문, 작전 일지, 전공 기록입니다. 낙동강 동안 방어선 구축과 관군과의 연합 작전이 날짜별로 상술되어 있습니다.',
    significance: '왜란 초기 영남 북부 내륙의 호국 항쟁을 실록보다 구체적으로 증언하는 귀중한 전란 사료입니다.',
    tag: ['예안의병일기', '창의격문', '임진왜란', '의병', '호국'],
    sourceOrKeeper: '문중 고문서 / 한국학중앙연구원 연계'
  },
  {
    id: 'arch-hogowa-jib',
    title: '『호고와집(互古窩集)』 목판',
    hanjaTitle: '互古窩集 木板',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 순조 연간 (1800년대 초반)',
    location: '한국국학진흥원 장판각 (유교책판)',
    imageUrl: '/images/archives/hogowa_jib.jpg',
    description: '수곡파 학자 호고와 류휘문(1773~1827) 선생의 문집 목판입니다. 정재 류치명 선생의 종형이자 퇴계 이황 학통을 계승한 학자로, 성리학 심성론의 정치(精緻)한 분석과 향촌 사림의 교화 방안을 담고 있습니다.',
    significance: '유네스코 세계기록유산 유교책판 목록에 수록되어 있으며, 19세기 영남 성리학파의 사상적 성취를 보여줍니다.',
    tag: ['호고와집', '류휘문', '유교책판', '한국국학진흥원', '성리학'],
    sourceOrKeeper: '한국국학진흥원 장판각'
  },
  {
    id: 'arch-musil-jeongryeogak',
    title: '전주류씨 무실정려각(務實旌閭閣)',
    hanjaTitle: '全州柳氏 務實旌閭閣',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 인조 13년 (1635년 건립, 1988년 수몰 이건)',
    location: '경상북도 안동시 임동면 수곡용계로 400',
    imageUrl: '/images/archives/musil_jeongryeogak.jpg',
    description: '무실 입향조 류성 선생의 배위이자 학봉 김성일의 누이인 의성 김씨의 정절을 기려 인조 임금이 정려를 내려 건립한 비각입니다. 1988년 임하댐 수몰로 현재의 고지대로 원형 이건되었습니다.',
    significance: '경상북도 민속문화유산 제48호로, 수곡파 가문과 의성 김씨 문중 간의 혼반 연대와 조선 중기 정절 문화를 대변하는 대표 유적입니다.',
    tag: ['무실정려각', '정려각', '의성김씨', '민속문화유산', '임하댐 이건'],
    sourceOrKeeper: '경상북도 민속문화유산'
  },
  {
    id: 'arch-yongwa-jongtaek',
    title: '전주류씨 용와종택(慵窩宗宅) 및 침간정(枕澗亭)',
    hanjaTitle: '全州柳氏 慵窩宗宅 및 枕澗亭',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 영조 연간 (1987년 구미 일선리 이건)',
    location: '경상북도 구미시 해평면 일선리 (문화재마을)',
    imageUrl: '/images/archives/yongwa_jongtaek.jpg',
    description: '수곡파의 석학 용와 류승현(1680~1746) 선생의 종택과 부속 정자입니다. 본래 무실 인근 박곡리에 있었으나 1987년 임하댐 건설로 문중이 집단 이주지인 구미 일선리 문화재마을로 원형 그대로 해체 이건하였습니다.',
    significance: '경상북도 민속문화유산 제18호로, 수몰로 인해 고향을 떠나야 했던 수곡파의 아픈 이건사이자 영남 사대부 가옥의 미학을 증명합니다.',
    tag: ['용와종택', '침간정', '류승현', '일선리 문화재마을', '민속문화유산'],
    sourceOrKeeper: '경상북도 민속문화유산'
  },
  {
    id: 'arch-dongamjeong',
    title: '동암정(東巖亭)',
    hanjaTitle: '東巖亭',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 정조 연간 (1987년 구미 일선리 이건)',
    location: '경상북도 구미시 해평면 일선리 (문화재마을)',
    imageUrl: '/images/archives/dongamjeong.jpg',
    description: '유네스코 세계기록유산 『상변통고』를 집필한 동암 류장원(1724~1796) 선생이 후학을 가르치고 학문을 연마하던 정자입니다. 임하댐 수몰을 피해 구미 일선리 문화재마을로 옮겨졌습니다.',
    significance: '경상북도 문화유산자료 제62호로, 조선 예학의 거봉이 머물던 학술 산실로서의 높은 역사적 가치를 지닙니다.',
    tag: ['동암정', '동암 류장원', '상변통고', '문화유산자료', '일선리 이건'],
    sourceOrKeeper: '경상북도 문화유산자료'
  },
  {
    id: 'arch-samgajeong',
    title: '삼가정(三嘉亭)',
    hanjaTitle: '三嘉亭',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 후기 (1987년 구미 일선리 이건)',
    location: '경상북도 구미시 해평면 일선리 (문화재마을)',
    imageUrl: '/images/archives/samgajeong.jpg',
    description: '수곡파 삼가공 류봉시(柳鳳時) 선생의 덕을 기리기 위해 문중 후손들이 건립한 정자입니다. 임하댐 수몰 당시 구미 일선리 문화재마을로 이건되어 보존되고 있습니다.',
    significance: '경상북도 문화유산자료 제50호로, 수곡파 종중의 정자 문화와 일선리 집단 이건 역사를 보여줍니다.',
    tag: ['삼가정', '류봉시', '문화유산자료', '일선리 이건'],
    sourceOrKeeper: '경상북도 문화유산자료'
  },
  {
    id: 'arch-jeongjae-jongtaek',
    title: '안동 정재종택(定齋宗宅) 및 정재문집(定齋文集)',
    hanjaTitle: '安東 定齋宗宅 및 定齋文集',
    category: 'historic_site',
    categoryLabel: '유적·종택',
    dateOrEra: '조선 후기 (18~19세기)',
    location: '경상북도 안동시 임동면 수곡리',
    imageUrl: '/images/archives/jeongjae_jongtaek.jpg',
    description: '영남 남인 사림의 영수로 퇴계-갈암 학통을 계승한 정재 류치명(柳致明, 1777~1861) 선생의 종택과 문집 목판 유산입니다. 이조참판, 대사헌을 지내며 영남 사림의 척사위정론과 정통 성리학을 주도하였습니다.',
    significance: '경상북도 기념물 제170호로 지정되어, 19세기 조선 사상계와 영남학파의 중심지 역할을 했던 수곡파의 학문적 위상을 증언합니다.',
    tag: ['정재종택', '정재 류치명', '기념물', '영남학파'],
    sourceOrKeeper: '경상북도 기념물 (수곡파 정재문중)'
  },
  {
    id: 'arch-jeongjae-woodblocks',
    title: '『정재선생문집(定齋先生文集)』 목판 (유네스코 세계기록유산)',
    hanjaTitle: '定齋先生文集 木板 (UNESCO 世界記錄遺産)',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 고종 연간 (1880년대 판각 간행)',
    location: '한국국학진흥원 장판각 (유교책판)',
    imageUrl: '/images/archives/jeongjae_woodblocks.jpg',
    description: '19세기 영남 성리학의 최고봉이자 퇴계학맥의 정통 계승자인 정재 류치명(1777~1861) 선생의 전 저작을 망라한 32권 16책 규모의 문집 목판입니다. 사단칠정론, 심성론, 척사위정론 등 조선 말기 지식인 사회의 사상적 격변과 도덕적 결단을 고스란히 담고 있습니다.',
    significance: '경상북도 유형문화유산 제171호 및 2015년 유네스코 세계기록유산(유교책판)으로 등재된 조선 사상사 최고의 1급 학술 문화유산입니다.',
    tag: ['정재선생문집', '정재 류치명', '유교책판', '세계기록유산', '유형문화유산', '한국국학진흥원'],
    sourceOrKeeper: '한국국학진흥원 장판각 (경북 유형문화유산 제171호)'
  },
  {
    id: 'arch-gyoji-document',
    title: '조선 국왕 사령 교지(敎旨) 및 고신(告身)',
    hanjaTitle: '朝鮮 國王 辭令 敎旨 및 告身',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 숙종~영조~정조 연간',
    location: '한국국학진흥원 수곡종택 기탁 고문서군',
    imageUrl: '/images/archives/gyoji_document.jpg',
    description: '조선 국왕이 수곡파 역대 선조(기봉 류복기, 삼산 류정원, 정재 류치명 등)에게 대사헌, 이조참판, 증직 등의 관직을 제수하며 내린 국왕 사령 공문서입니다. 국왕의 어보인 ‘시명지보(施命之寶)’가 선명히 날인되어 있으며, 국가의 공식 통치 체계 속에서 가문의 공신력과 정치적 위상을 확증합니다.',
    significance: '국왕의 어인과 관직 제수 내력이 완벽하게 보존된 조선왕조 1차 공문서로, 국가 소멸 시에도 가문의 역사적 지위를 입증하는 법적·제도적 기록물입니다.',
    tag: ['교지', '고신', '시명지보', '대사헌', '이조참판', '한국국학진흥원'],
    sourceOrKeeper: '수곡종택 기탁 고문서 (한국국학진흥원 수장고)'
  },
  {
    id: 'arch-hojeok-document',
    title: '수곡파 호적단자(戶籍單子) 및 준호구(准戶口)',
    hanjaTitle: '水谷派 戶籍單子 및 准戶口',
    category: 'document',
    categoryLabel: '문헌·고서',
    dateOrEra: '조선 숙종~고종 연간 (17~19세기)',
    location: '한국학중앙연구원 / 한국국학진흥원 기탁',
    imageUrl: '/images/archives/hojeok_document.jpg',
    description: '예안현(禮安縣)과 안동부(安東府) 관청에 3년마다 제출하여 공인을 받은 수곡파 종가의 호적 공문서입니다. 호주와 처의 4조(부·조·증조·외조), 동거 자녀, 솔거 노비의 명단과 나이가 먹으로 정밀하게 기록되어 있어, 수백 년간 이어진 무실 종가의 가계 구성과 혈통 계승을 실증합니다.',
    significance: '조선시대 호적 제도의 운영 실태와 가계의 혈통·사회경제적 실상을 증언하는 대체 불가능한 1차 인구·가족사 공문서입니다.',
    tag: ['호적단자', '준호구', '예안현', '4조', '고문서', '한국국학진흥원'],
    sourceOrKeeper: '전주류씨 무실종가 기탁 고문서 (한국국학진흥원)'
  }
];

// 4. 역사 타임라인
export const TIMELINE: TimelineEvent[] = [
  {
    year: '고려조',
    title: '전주류씨 시조 완산백(完山伯) 류혼 공 탄생 및 본관 확립',
    category: 'origin',
    description: '완산(전주)을 본향으로 삼고 충의와 도의를 가훈으로 삼아 번창하기 시작함.'
  },
  {
    year: '1300년대 말',
    title: '완산부원군 류습 공의 오자급제(五子及第)',
    category: 'origin',
    description: '다섯 아들이 모두 대과에 급제하여 명문 사대부 가문으로 확고한 위상을 정립함.'
  },
  {
    year: '1500년대 중엽',
    title: '기봉 류복기 선생 안동 수곡(무실) 입향',
    category: 'settlement',
    description: '예안 수곡리에 정착하여 400여 년간 번성할 영남 명문 집성촌 ‘무실마을’의 역사가 시작됨.'
  },
  {
    year: '1592년',
    title: '임진왜란 발발 및 예안 의병 창의(倡義)',
    category: 'achievement',
    description: '기봉 류복기 선생이 향내 선비들과 함께 예안의병을 결성하여 낙동강 방어선을 수호함.'
  },
  {
    year: '1700년대 중엽',
    title: '삼산 류정원 선생의 학문 융성과 『삼산집』 저술',
    category: 'achievement',
    description: '사헌부 대사헌을 지내며 퇴계 이황의 정통 성리학을 계승, 영남 사림의 영수로 추앙받음.'
  },
  {
    year: '1919년',
    title: '3·1운동과 유림 파리장서 독립청원 서명',
    category: 'achievement',
    description: '서산 류필영 선생을 비롯한 문중 인물들이 독립선언서에 서명하고 만주 무장투쟁 지원에 헌신함.'
  },
  {
    year: '1970~1980년대',
    title: '안동댐·임하댐 건설과 무실 집성촌 수몰',
    category: 'tragedy',
    description: '1970년대 안동댐에 이어 1980년대 후반 임하댐 담수로 인해 400여 년의 집성촌 마을 전역이 물속에 잠김. 무실종택, 기양서당, 수애당 등 종중 고택들은 현재의 고지대로 해체 이건되고 수많은 문중인들이 전국으로 흩어짐.'
  },
  {
    year: '현재',
    title: '전주류씨 디지털 오픈 아카이브 출범',
    category: 'archive',
    description: '물리적 공간이 사라져도 남아 있을, 가문의 모든 기록과 정신을 글로벌 오픈 저장소(GitHub)에 영구 보존하는 디지털 문헌 프로젝트 개시.'
  }
];
